services:
  hotelreservationapi-presentation:
    image: hotelreservationapi-presentation:latest
    container_name: hotelreservationapi-presentation
    build:
      context: ./Presentation/HotelReservationAPI.Presentation
      dockerfile: Dockerfile
    secrets:
      - stripe_secret_key

    ports:
      - "8080:80"
    restart: "unless-stopped"

  postgresql:
    image: postgres:16
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emreraftongame63
      POSTGRES_DB: HotelReservationDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "unless-stopped"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: [
        "redis-server",
        "--maxmemory", "512mb",
        "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Emre123!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  pgdata:
secrets:
    stripe_secret_key:
        external: true
