services:
  hotelreservationapi.presentation:
    image: ${DOCKER_REGISTRY-}hotelreservationapipresentation
    build:
      context: .
      dockerfile: Presentation/HotelReservationApi.Presentation/Dockerfile
    secrets:
      - jwt_secret
      - stripe_secret_key
      - db_password
    depends_on:
      - hotelreservationapi.database
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
  hotelreservationapi.database:
    image: postgres:18-alpine
    container_name: hotelreservationapi.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emreraftongame63
      POSTGRES_DB: hotelreservationdb
    ports:
      - "5432:5432"
    volumes:
      - hotelreservation-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine 
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: gizlirabbitmqadminsifre123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    restart: unless-stopped
volumes:
  hotelreservation-data:
  rabbitmq_data:

secrets:
  jwt_secret:
    external: true
  stripe_secret_key:
    external: true
  db_password:
    external: true
