services:
  hotelreservationapi-presentation:
    image: hotelreservationapi-presentation:latest
    build:
      context: .
      dockerfile: Presentation/HotelReservationApi.Presentation/Dockerfile
    secrets:
      - stripe_secret_key
      - jwt_secret
      - smtp_app_pass
      - rabbitmq_user 
      - db_password
      - rabbitmq_password
    ports:
      - "8082:8080"
    restart: unless-stopped
    depends_on:
      - postgresql
      - rabbitmq 
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      SMTP_USER: "hotelapideneme@gmail.com"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_PASSWORD_FILE: "/run/secrets/smtp_app_pass"



  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: [
        "redis-server",
        "--maxmemory", "512mb",
        "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - "6379:6379"
  postgresql:
    image: postgres:18.1
    secrets:
      - db_password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: HotelReservationDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.8
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    secrets:
      - rabbitmq_user
      - rabbitmq_password
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  rabbitmq_data:
  pgdata:
secrets:
    stripe_secret_key:
        file: ./secrets/stripe_secret_key.txt
    jwt_secret:
        file: ./secrets/jwt_secret.txt
    rabbitmq_user:
        file: ./secrets/rabbitmq_user.txt
    rabbitmq_password:
        file: ./secrets/rabbitmq_password.txt
    smtp_app_pass:
        file: ./secrets/smtp_app_pass.txt
    db_password:
        file: ./secrets/db_password.txt
