services:
  hotelreservationapi-presentation:
    image: hotelreservationapi-presentation:latest
    container_name: hotelreservationapi-presentation
    build:
      context: ./Presentation/HotelReservationAPI.Presentation
      dockerfile: Dockerfile
    secrets:
      - stripe_secret_key
      - jwt_secret
      - db_password 
    ports:
      - "8080:80"
    restart: "unless-stopped"

  postgresql:
    image: postgres:18.1
    container_name: postgresql
    secrets:
        - db_password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: HotelReservationDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: "unless-stopped"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: [
        "redis-server",
        "--maxmemory", "512mb",
        "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    secrets:
      - rabbitmq_user
      - rabbitmq_password
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_user
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  rabbitmq_data:
  pgdata:
secrets:
    stripe_secret_key:
        external: true
    db_password:
        external: true
    jwt_secret:
        external: true
    rabbitmq_user:
        external: true
    rabbitmq_password:
        external: true
